published/Models/PaginacionViewModel.cs
namespace ControlDeFinanzas.Models
{
    public class PaginacionViewModel
    {

        public int Pagina { get; set; } = 1;
        //cantidad por defecto de elementos que habrá en un página
        private int recordsPorPagina = 10;
        //cantidad maxima de elemento ue habrá en una página
        private int cantidadMaximaRecordsPorPagina = 50;

        public int RecordsPorPagina
        {
            get
            {
                return recordsPorPagina;
            }
            set
            //operador ternario: sie el valor que me manda el usuario de cantidad de registros por página es mayor que
            //cantidadMaximaRecordPorPagina entonces por defecto muesto la cantidad máxima (50) 
            //sino muestor el valor si value es 70 se pasa de 50 y muestro 50 si values es 10 muestro 10
            {
                recordsPorPagina = (value > cantidadMaximaRecordsPorPagina)
                    ? cantidadMaximaRecordsPorPagina : value;
            }
            //registro a saltar de página en página


        }
        public int RecordsASaltar => recordsPorPagina * (Pagina - 1);
    }
}

published/Models/ReporteTransaccionesDetalladas.cs
namespace ControlDeFinanzas.Models
{
    //modelo para mostrar al usuario
    public class ReporteTransaccionesDetalladas
    {
        public DateTime FechaInicio { get; set; }
        public DateTime FechaFin { get; set; }
        public IEnumerable<TransaccionesPorFecha> TransaccionesAgrupadas { get; set; }
        public decimal BalanceDepositos => TransaccionesAgrupadas.Sum(x => x.BalanceDepositos);
        public decimal BalanceRetiros => TransaccionesAgrupadas.Sum(x => x.BalanceRetiros);
        public decimal Total => BalanceDepositos - BalanceRetiros;
        //creo una clase interna pq solo la voy a usar aquí
        public class TransaccionesPorFecha
        {
            public DateTime FechaTransaccion { get; set; }
            public IEnumerable<Transaccion> Transacciones { get; set; }
            public decimal BalanceDepositos => Transacciones.Where(x => x.TipoOperacionId == TipoOperacion.Ingreso).Sum(x => x.Monto);
            public decimal BalanceRetiros => Transacciones.Where(x => x.TipoOperacionId == TipoOperacion.Gasto).Sum(x => x.Monto);
        }

    }
}

published/Models/ResumenMontosViewModel.cs
namespace ControlDeFinanzas.Models
{
    public class ResumenMontosViewModel
    {
        public decimal Ingresos { get; set; }
        public decimal Gastos { get; set; }
        public decimal Total { get; set; }
    }
}

published/Controllers/CuentasController.cs
using AutoMapper;
using ControlDeFinanzas.Models;
using ControlDeFinanzas.Servicios;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ControlDeFinanzas.Controllers
{
    public class CuentasController : Microsoft.AspNetCore.Mvc.Controller
    {
        private readonly IRepositorioTiposCuentas repositorioTiposCuentas;
        private readonly IServicioUsuarios servicioUsuarios;
        private readonly IRepositorioCuentas repositorioCuentas;
        private readonly IMapper mapper;
        private readonly IRepositorioTransacciones repositorioTransacciones;
        private readonly IServicioReportes servicioReportes;

        //inyecto automaper para poder usarlo
        public CuentasController(IRepositorioTiposCuentas repositorioTiposCuentas, IServicioUsuarios servicioUsuarios, IRepositorioCuentas repositorioCuentas,
            IMapper mapper, IRepositorioTransacciones repositorioTransacciones, IServicioReportes servicioReportes)
        {
            this.repositorioTiposCuentas = repositorioTiposCuentas;
            this.servicioUsuarios = servicioUsuarios;
            this.repositorioCuentas = repositorioCuentas;
            this.mapper = mapper;
            this.repositorioTransacciones = repositorioTransacciones;
            this.servicioReportes = servicioReportes;
        }

        public async Task<IActionResult> Index()
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var cuentaConTipoCuenta = await repositorioCuentas.Buscar(usuarioId);

            var modelo = cuentaConTipoCuenta
                //como puede haber varios con elmismo tipo cuenta los agrupo por el tipo cuenta
                .GroupBy(x => x.TipoCuenta)
                //hago una proyeccion hacia IndiceCuentasViewModel
                .Select(grupo => new IndiceCuentasViewModel
                {
                    //key es tipo cuenta
                    TipoCuenta = grupo.Key,
                    //grupo.AsEnumerable es el IEnumerable de tiposcuentas
                    Cuentas = grupo.AsEnumerable()
                }
                ).ToList();
            return View(modelo);

        }

        [HttpGet]
        public async Task<IActionResult> Crear()
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();

            var modelo = new CuentaCreacionViewModel();
            //HAGO UN MAPEO DE TIPOCUENTA A SELECTLISTIDEM
            modelo.TiposCuentas = await ObtenerTiposCuentas(usuarioId);
            return View(modelo);
        }

        [HttpPost]
        public async Task<IActionResult> Crear(CuentaCreacionViewModel cuenta)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            //valido que el tipo cuenta que envia elusuario es valido para el usuarioId
            var tipoCuenta = await repositorioTiposCuentas.ObtenerPorId(cuenta.TipoCuentaId, usuarioId);

            if (tipoCuenta == null)
            {
                return RedirectToAction("NoEnontrado", "Index");
            }

            if (!ModelState.IsValid)
            {
                cuenta.TiposCuentas = await ObtenerTiposCuentas(usuarioId);
                return View(cuenta);
            }

            await repositorioCuentas.crear(cuenta);
            return RedirectToAction("Index");

        }
        public async Task<IActionResult> Editar(int id)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var cuenta = await repositorioCuentas.ObtenerPorId(id, usuarioId);

            //Me ASEGURO DE QUE LA CUENTA EXISTE
            if (cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            //armo el modelo que se espera y utilizo automapper para mapear de cuenta a CuentaCreacionViewModel
            var modelo = mapper.Map<CuentaCreacionViewModel>(cuenta);


            modelo.TiposCuentas = await ObtenerTiposCuentas(usuarioId);
            return View(modelo);
        }
        [HttpPost]
        public async Task<IActionResult> Editar(CuentaCreacionViewModel cuentaEditar)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var cuenta = await repositorioCuentas.ObtenerPorId(cuentaEditar.Id, usuarioId);

            //confirmo que existe
            if (cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            var tipoCuenta = await repositorioTiposCuentas.ObtenerPorId(cuentaEditar.TipoCuentaId, usuarioId);

            if (tipoCuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            await repositorioCuentas.Actualizar(cuentaEditar);
            return RedirectToAction("Index");
        }
        //creo como siempre las acciones get y post en este caso para borrar
        [HttpGet]
        public async Task<IActionResult> borrar(int id)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var cuenta = await repositorioCuentas.ObtenerPorId(id, usuarioId);

            if (cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            return View(cuenta);
        }
        //en post en donde se realiza el borrado
        [HttpPost]
        public async Task<IActionResult> BorrarCuenta(int id)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var cuenta = await repositorioCuentas.ObtenerPorId(id, usuarioId);
            var transacciones = await repositorioTransacciones.listaTransaccionesCuenta(usuarioId);

            if (cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            foreach (var transaccion in transacciones)
            {
                if (cuenta.Id == transaccion.CuentaId)
                {
                    return RedirectToAction("BorrarTipoCuentaUsada", "Home");
                }
            }


            await repositorioCuentas.Borrar(id);
            return RedirectToAction("Index");

        }
        private async Task<IEnumerable<SelectListItem>> ObtenerTiposCuentas(int usuarioId)
        {
            var tiposCuentas = await repositorioTiposCuentas.Obtener(usuarioId);
            return tiposCuentas.Select(x => new SelectListItem(x.Nombre, x.Id.ToString()));

        }

        public async Task<IActionResult> Detalle(int id, int mes, int año)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var cuenta = await repositorioCuentas.ObtenerPorId(id, usuarioId);

            if (cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }


            ViewBag.Cuenta = cuenta.Nombre;

            var modelo = await servicioReportes.ObtenerReporteTransaccionesDetalladasPorCuenta(usuarioId, id, mes, año, ViewBag);

            return View(modelo);
        }


    }
}

published/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ControlDeFinanzas</title>
    <link rel="icon" type="image/x-icon" href="~/logo.ico">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
@*    <link rel="stylesheet" href="~/ControlDeFinanzas.styles.css" asp-append-version="true" />*@
    <link rel="stylesheet" href="~/css/custom.css" asp-append-version="true" />
@*    <link rel="stylesheet" href="ContolDeFinanzas.styles.css" asp-append-version="true" />*@
    <link rel="stylesheet" href="~/lib/fullcalendar/main.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Transacciones" asp-action="Index">ControlDeFinanzas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Transacciones" asp-action="Index">Transacciones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Cuentas" asp-action="Index">Cuentas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="TiposCuentas" asp-action="Index">Tipos Cuentas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="categorias" asp-action="Index">Categorias</a>
                        </li>

                    </ul>
                    @*Coloco la vista parcial login*@
                    <partial name="_LinksLogin" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ControlDeFinanzas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @*Coloco aquí el script de la libreria de JQUERYUI*@
    <script src="~/lib/jquery-ui-1.13.2/jquery-ui-1.13.2/jquery-ui.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

published/Views/Shared/_LinksLogin.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Usuario> SignInManager

<ul class="navbar-nav">
    @*Si el usuario esta autenticado*@
    @if (SignInManager.IsSignedIn(User))
    {
        @*Si lo esta muestro su nombre*@
        <li class="nav-item">
            <span class="nav-link text-dark">HOLA, @User.Identity.Name</span>
        </li>
        //formulario para deslogearse
        <li class="nav-item">
            <form class="form-inline" asp-action="logout" asp-controller="usuarios"> 
                <button type="submit" class="nav-link btn btn-link text-dark" >Logout</button>

            </form>

        </li>
        
    }else
    {
        //sino, rededirijo al usuario a otro menu para registrarse
        <li class="nav-item">
            <a class="nav-link dark-text" asp-controller="usuarios" asp-action="Registro">
                Registro
            </a>
            <a class="nav-link dark-text" asp-controller="usuarios" asp-action="Login">
                Login
            </a>

        </li>
        
    }
</ul>

published/Views/Shared/_NavegarPorMeses.cshtml
@model DateTime


@*Creo un navegador de meses*@
<h4>
    <a asp-route-mes="@ViewBag.mesAnterior" asp-route-año="@ViewBag.añoAnterior"
    class="btn btn-secondary"><i class="bi-chevron-left"></i>
    </a>
    @Model.ToString("MMM")-@Model.Year
    <a asp-route-mes="@ViewBag.mesPosterior" asp-route-año="@ViewBag.añoPosterior"
    class="btn btn-secondary"><i class="bi-chevron-right"></i>
    </a>
</h4>

published/Views/Shared/_Paginacion.cshtml
@model PaginacionRespuesta

@{
    var plantillaLink = string.Concat(Model.BaseURL, "?pagina={0}&recordsPorPagina={1}");
    var activarBotonAnterior = Model.Pagina > 1;
    var activarBotonSiguiente = Model.Pagina < Model.CantidadTotalDePaginas;
}

<nav>
    <ul class="pagination">
        @*Boton para navegar hacia atrás*@
        @*Con disabled desbloqueo el botón cuando ste en la pg 1*@
        <li class="page-item @(activarBotonAnterior ? null : "disabled")">
            @if (activarBotonAnterior)
            {
               <a class="page-link" href="@string.Format(plantillaLink, Model.Pagina -1, Model.RecordsPorPagina)">
                Anterior

                </a>
            }
            else
            {
                <span class="page-link">Anterior</span>
            }

        </li> 

            
            

        @for (var pagina = 1; pagina <= Model.CantidadTotalDePaginas; pagina++)
        {
            //lógica. si la página actual es donde se encuentra el usuario la ilumino si no, no
            <li class="page-item @(pagina == Model.Pagina ? "active" : null)">
                <a class="page-link" href="@string.Format(plantillaLink, pagina, Model.RecordsPorPagina)">
                    @pagina

                </a>

            </li>

        
        }
        @*Boton para navegar hacia adelante*@
        @*Con disabled desbloqueo el botón cuando ste en la última pg*@
        <li class="page-item @(activarBotonSiguiente ? null : "disabled")">
            @if (activarBotonSiguiente)
            {
                <a class="page-link" href="@string.Format(plantillaLink, Model.Pagina +1, Model.RecordsPorPagina)">
                    Siguiente

                </a>
            }
            else
            {
                <span class="page-link">Siguiente</span>
            }

                

            </li>
    </ul>
</nav>

published/Views/Shared/_ReporteTransaccionesDetalladas.cshtml
@model ReporteTransaccionesDetalladas
@{
    var resumenMontos = new ResumenMontosViewModel()
            {
                Ingresos = Model.BalanceDepositos,
                Gastos = Model.BalanceRetiros,
                Total = Model.Total

            };
}


@*uso las vista parcial*@
<partial name="_NavegarPorMeses" model="@Model.FechaInicio" />
<partial name="_ResumenMontos" model="@resumenMontos" />




@*Muestro un mensaje al usuario en caso de no haber transaciones*@
@if (Model.TransaccionesAgrupadas.Count()==0){

    <h5>No hay datos para mostrar</h5>
}
else{
    <table class="table">
        <tbody>
            @foreach(var transacionAgrupada in Model.TransaccionesAgrupadas)
            {
                <tr style="background-color: lightblue; font-size: 26px">
                    <td colspan="3">@transacionAgrupada.FechaTransaccion.Day
                        <span class="badge bg-secondary">
                            @transacionAgrupada.FechaTransaccion.ToString("ddd")
                        </span>
                    </td>
                    <td class="activo">@transacionAgrupada.BalanceDepositos.ToString("N")</td>
                    <td class="pasivo">@transacionAgrupada.BalanceRetiros.ToString("N")</td>
                </tr>
                @foreach (var transaccion in transacionAgrupada.Transacciones)
                {
                    <tr style="vertical-aling: middle">
                        <td>
                            <a asp-controller="transacciones" asp-action="Editar" asp-route-id="@transaccion.Id" asp-route-urlRetorno="@ViewBag.urlRetorno">
                                <i class="bi-pencil"></i>
                            </a>
                        </td>
                        <td>@transaccion.Categoria</td>
                        <td>@transaccion.Cuenta</td>
                        <td class="activo">@(transaccion.TipoOperacionId == TipoOperacion.Ingreso ? transaccion.Monto.ToString("N") : null)</td>
                        <td class="pasivo">@(transaccion.TipoOperacionId == TipoOperacion.Gasto ? transaccion.Monto.ToString("N") : null)</td>
                    </tr>
                }


        }
        </tbody>

    </table>

}

published/Views/Shared/_ResumenMontos.cshtml
@model ResumenMontosViewModel
<div class="contenedor-totales mb-3 ">
    <div>
        <div>
            <strong>Depósitos</strong>
        </div>
        <div class="activo">
            @Model.Ingresos.ToString("N")
        </div>

    </div>
    <div>
        <div>
            <strong>Retiros</strong>
        </div>
        <div class="pasivo">
            @Model.Gastos.ToString("N")
        </div>

    </div>
        <div>
        <div>
            <strong>Total</strong>
        </div>
        <div >
            @Model.Total.ToString("N")
        </div>

    </div>
</div>